Feature/back 3 deleting teams
cmu-dsc/poker-backend-2025 pull request #1
Opened 2024-09-28 17:07 UTC by ryrywan

We edited the files to match the new data schema we decided on. However, for some reason, threre's some mismatch with the schema.prisma, and the "where" clauses are bugged. Also, we were able to implement a delete teams function, but when trying to set the team members to an empty array (to remove the members from the team) it causes an error.

2024-09-28 17:25 UTC, clementou requested changes

2024-09-28 17:25 UTC, clementou commented on README.md
> +    UserDao "1" -- "0..1" TeamDao
missing association names

2024-09-28 17:25 UTC, clementou commented on README.md
> +        +DateTime sendAt
should be sentAt

2024-09-28 17:25 UTC, clementou commented on web-backend/.env.example
I don't think we want to commit this?

2024-09-28 17:25 UTC, clementou commented on web-backend/db/db.sqlite3
We do not want to commit this.

2024-09-28 17:25 UTC, clementou commented on web-backend/src/controllers/matchController.ts
don't commit commented out code

2024-09-28 17:25 UTC, clementou commented on web-backend/src/middleware/auth/firebaseAuth.ts
don't commit commented-out code, we can always revert if we need it back

2024-09-28 17:25 UTC, clementou commented on web-backend/src/services/validators/teamValidatorService.ts
> +  id: z.number().int().min(0).optional(),
should this be optional?

2024-09-28 17:29 UTC, sirtobsi commented on web-backend/.env.example
no, this is fine! .env.example is just giving the layout - not secrets.

2024-09-28 17:34 UTC, sirtobsi commented on web-backend/src/controllers/matchController.ts
> +  // res.status(200).json({ downloadUrl, filetype: 'txt' } as DownloadLinkDto)
don't commit commented out code

2024-09-28 17:45 UTC, sirtobsi requested changes
the getTeam endpoint should not return deleted teams!

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/services/teamService.ts
> +  teamName: string,
type in doctoring and function do not match

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/services/teamService.ts
> +  if (team.teamName !== teamName) {
please compare the id and not a name. A name is not necessarily unique!

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/prisma/schema.prisma
> +  teamName        String            @unique
is there a reason for the decision to make the team name unique?

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +    await createServiceAccountAndResources(teamName)
remove this - the functionality is no longer needed.

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +  team.name = team.name.toLowerCase()
we shouldn't change the name of the team! Please use the ID as an unique identifier.

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +  team.name = team.name.toLowerCase()
we should validate the ID instead of the name.

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +  const team: TeamDao = await getTeamById(teamName)
the team name is not the ID

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +  const teamName: string = validateTeamName(req.params.teamName)
use the team id and validate the id instead of the name

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
>    const githubName: string = validateTeamName(req.params.githubUsername)
this needs to be changed to the team id

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/controllers/teamController.ts
> +  team.githubUsername = teamId
why does team still have a githubUsername?

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/services/teamService.ts
>    await dbClient.teamDao.delete({
you shouldn't delete the team but rather update the deleted flag to true

2024-09-28 17:45 UTC, sirtobsi commented on web-backend/src/services/validators/teamValidatorService.ts
> +  id: z.number().int().min(0).optional(),
imo no. Is is set to required in the api spec anyways!

2024-09-28 18:40 UTC, sirtobsi commented on README.md
> +        +DateTime sendAt
ey, don't call me out on my mediocre English :P

2024-10-07 19:40 UTC, sirtobsi commented
@ryrywan @Tchegnoncool 

One of you wanted to push the requested changes?

2024-10-11 00:01 UTC, sirtobsi commented
Covered in #7

2024-10-11 00:01 UTC, closed without merging